version: '3.8'

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "9999:9999"
  #   depends_on:
  #     - api1
  #     - api2
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin 
      MYSQL_PASSWORD: senha123
      MYSQL_DATABASE: rinha2024q1
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3308:3306"
    volumes:
      - ./MySQL_initdb.d/:/docker-entrypoint-initdb.d/

  # api1:
  #   image: rinha2024q1
  #   ports:
  #     - "8080:80" 
  #   depends_on:
  #     - db